import { createClient } from 'npm:@supabase/supabase-js@2'
const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!)
const BUCKET='community-med-photos'
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'}
const clean=(v:unknown)=>String(v??'').trim().replace(/\s+/g,' ')
async function household(code:string){const {data}=await db.from('households').select('id,display_name').eq('share_code',clean(code).toUpperCase().replace(/[\s-]/g,'')).single();if(!data)throw Error('that code is not valid');return data}
const safe=(r:any)=>({id:r.id,name:r.name,strength:r.strength,hasPillPhoto:!!r.pill_photo_path,hasPacketPhoto:!!r.packet_photo_path})
async function bytes(s?:string){if(!s)return null;const b=Uint8Array.from(atob(s),c=>c.charCodeAt(0));if(b.length>512000)throw Error('photo too large');return b}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const b=await req.json();const submitter=await household(b.code)
if(b.action==='search'){const q=clean(b.query).toLowerCase();if(q.length<3)return Response.json({references:[]},{headers:cors});const {data,error}=await db.from('community_medicine_references').select('id,name,strength,pill_photo_path,packet_photo_path').eq('status','active').ilike('name_search',q+'%').order('name').limit(6);if(error)throw error;return Response.json({references:(data||[]).map(safe)},{headers:cors})}
if(b.action==='urls'){const {data:r,error}=await db.from('community_medicine_references').select('pill_photo_path,packet_photo_path').eq('id',b.referenceId).eq('status','active').single();if(error||!r)throw Error('reference not found');const out:any={pill:null,packet:null};for(const k of ['pill','packet']){const p=r[k+'_photo_path'];if(p){const {data,error:e}=await db.storage.from(BUCKET).createSignedUrl(p,300);if(e)throw e;out[k]=data.signedUrl}}return Response.json(out,{headers:cors})}
if(b.action==='publish'){const name=clean(b.name),strength=clean(b.strength);if(!name||name.length>100||strength.length>60)throw Error('invalid medicine details');const ns=name.toLowerCase(),ss=strength.toLowerCase();let ref:any=null;if(b.referenceId){const found=await db.from('community_medicine_references').select('*').eq('id',b.referenceId).eq('status','active').single();if(found.error)throw found.error;ref=found.data;if(ref.name_search!==ns||ref.strength_search!==ss)throw Error('community name and strength cannot be changed')}else{const old=await db.from('community_medicine_references').select('*').eq('name_search',ns).eq('strength_search',ss).maybeSingle();if(old.error)throw old.error;if(old.data)return Response.json({kind:'duplicate',reference:safe(old.data)},{headers:cors});const made=await db.from('community_medicine_references').insert({name,strength,name_search:ns,strength_search:ss}).select('*').single();if(made.error)throw made.error;ref=made.data}const added:string[]=[],needsReview:string[]=[];for(const k of ['pill','packet']){const raw=await bytes(b[k+'PhotoBase64']);if(!raw)continue;if(ref[k+'_photo_path']){needsReview.push(k);continue}const path=`references/${ref.id}/${k}/${crypto.randomUUID()}.jpg`;const up=await db.storage.from(BUCKET).upload(path,raw,{contentType:'image/jpeg'});if(up.error)throw up.error;const patch:any={};patch[k+'_photo_path']=path;const u=await db.from('community_medicine_references').update(patch).eq('id',ref.id);if(u.error)throw u.error;added.push(k)}const fresh=await db.from('community_medicine_references').select('*').eq('id',ref.id).single();if(fresh.error)throw fresh.error;return Response.json({kind:b.referenceId?'updated':'created',reference:safe(fresh.data),added,needsReview},{headers:cors})}
if(b.action==='suggestReplacement'){if(b.confirmReplacement!==true||!['pill','packet'].includes(b.kind))throw Error('replacement confirmation required');const ref=await db.from('community_medicine_references').select('id').eq('id',b.referenceId).eq('status','active').single();if(ref.error)throw ref.error;const raw=await bytes(b.photoBase64);if(!raw)throw Error('photo required');const path=`suggestions/${crypto.randomUUID()}.jpg`;const up=await db.storage.from(BUCKET).upload(path,raw,{contentType:'image/jpeg'});if(up.error)throw up.error;const row=await db.from('community_photo_suggestions').insert({reference_id:ref.data.id,kind:b.kind,photo_path:path,submitted_by_household_id:submitter.id,submitted_by_name:submitter.display_name}).select('id,status').single();if(row.error)throw row.error;return Response.json({suggestion:row.data},{headers:cors})}
throw Error('unknown action')}catch(e){return Response.json({error:e?.message||'request failed'},{status:400,headers:cors})}})